# Generated by Django 3.0 on 2019-12-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20191213_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.FloatField(help_text='total time should be in minutes'),
        ),
    ]
