# Generated by Django 3.0 on 2019-12-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_pagination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagination',
        ),
    ]
