# Generated by Django 3.0 on 2019-12-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='time',
            new_name='total_time',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='time_per_question',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
    ]
