# Generated by Django 3.0 on 2019-12-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20191220_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='time_per_question',
            field=models.CharField(default='', max_length=10),
        ),
    ]
