# Generated by Django 3.0 on 2019-12-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20191220_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='time_per_question',
            field=models.IntegerField(default=0),
        ),
    ]
