# Generated by Django 3.0 on 2019-12-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['id'], name='questions_s_id_3bb024_idx'),
        ),
    ]
