# Generated by Django 3.0 on 2019-12-21 12:30

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['id'], name='questions_s_id_3bb024_idx'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Subject'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['id'], name='questions_q_id_18940f_brin'),
        ),
    ]
