# Generated by Django 3.0 on 2019-12-13 13:07

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=200)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('option', models.CharField(max_length=100)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer', models.CharField(max_length=100)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
        migrations.AddIndex(
            model_name='question',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['id'], name='questions_q_id_18940f_brin'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['id'], name='questions_o_id_642654_brin'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['id'], name='questions_a_id_83bb26_brin'),
        ),
    ]
