# Generated by Django 3.0 on 2019-12-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20191213_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='option1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='option',
            name='option2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='option',
            name='option3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='option',
            name='option4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
