# Generated by Django 3.0 on 2019-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagination',
            name='subject_id',
            field=models.IntegerField(null=True),
        ),
    ]
