# Generated by Django 3.0 on 2019-12-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagination', '0002_pagination_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagination',
            old_name='subject_id',
            new_name='exam_id',
        ),
    ]
