DEBUG = True
SECRET_KEY = 'a!c1tip_x1qnjzi!szges=xu^pi-u9a$q^d4q_i(_x58=5i0)j'
ALLOWED_HOSTS = []
ENGINE = 'django.db.backends.postgresql_psycopg2'
NAME = 'recruitment'
USER = 'ergo'
PASSWORD = 'ergoventures'
HOST = 'localhost'
PORT = ''
STATIC_URL = '/static/'
